language: python
cache: pip

python:
  - "3.5"


before_install:
  - pip install -U pip
  - pip install wheel
  - sudo apt-get update


env:
  global:
    - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
    - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels


install:
  - pip wheel -r requirements.txt
  - pip install -r requirements.txt


script:
  - py.test . --cov=./
  - flake8 ./
